adding first pass example embeddings logic
samgregson/GHPT-experiments pull request #11
Opened 2024-07-02 17:34 UTC by NicolasFranklin-MM

Creating semantic examples branch 

However, the feature is still WIP / incomplete, so thats why this is a draft

2024-07-05 15:35 UTC, NicolasFranklin-MM commented
Not sure where the best place to write some stuff about each commit in more detail, but:
- In commit _**[Examples / List{Example] fix] / d11cc7b:**_ 
Changed the pipe_strategy() method inside pipeline.py to accept "examples" which is a dynamic list of sorted examples by relevance (embedding)
Changed pipeline_prompts.py line about model.json.dump from examples.Examples to simply examples (because now we are casting to List[Example] not Examples
Changed examples.py to cast to List[Example] (I think there were some errors where it said List[Examples] or Examples. Fixed now.

![image](https://github.com/samgregson/GHPT-experiments/assets/90543642/2179e0fe-86ed-4923-bffa-8cfbc3e77bcc)

2024-07-08 16:31 UTC, samgregson requested changes
Nice work!

- [x] Please clear the output from the notebooks. I thought I'd implemented an auto clear but doesn't seem to have worked, unless you are missing a push?

- [ ] Could you add a unit test as discussed. i.e. copy what you did for the embeddings notebook into a python file and wrap it into a pytest function, assert that the examples get sorted by checking the first item in the list (e.g. cup example).

2024-07-08 16:31 UTC, samgregson commented on prompts/pipeline_prompts.py
> +        #[e.model_dump_json() for e in examples.Examples]
delete zombie code

2024-07-11 15:47 UTC, NicolasFranklin-MM commented
+ Add a test to ensure no embeddings (when doing k-nearest)  

- [ ] Add a test to ensure no embeddings (when doing k-nearest)  - use Assert -> check for e in examples, example.embeddings = None or just check the first one

2024-07-17 14:51 UTC, samgregson approved these changes

2024-07-17 15:21 UTC, merged